### ISSUE TITLE
JsonMappingException when Urls "u" is empty array

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/transitfeeds-client-library#1]
I'm currently seeing the following exception:

~~~
com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of edu.usf.cutr.transitfeeds.model.Urls out of START_ARRAY token
 at [Source: sun.net.www.protocol.http.HttpURLConnection$HttpInputStream@38c5cc4c; line: 150, column: 14] (through reference chain: edu.usf.cutr.transitfeeds.GetFeedsResponse["results"]->edu.usf.cutr.transitfeeds.model.Results["feeds"]->java.util.ArrayList[8]->edu.usf.cutr.transitfeeds.model.Feed["u"])

	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:216)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:873)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:869)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromArray(BeanDeserializerBase.java:1293)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:135)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:260)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:277)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:249)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:260)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:260)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1575)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1166)
	at edu.usf.cutr.transitfeeds.GetFeedsRequest.call(GetFeedsRequest.java:74)
	at edu.usf.cutr.transitfeeds.GetFeedsTest.testGetFeedsWithUrlArray(GetFeedsTest.java:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
~~~

When trying to parse this JSON:

~~~
{
"id": "translink-vancouver/397",
"ty": "gtfsrealtime",
"t": "TransLink Trip Updates",
"l": {
"id": 45,
"pid": 44,
"t": "Vancouver, BC, Canada",
"n": "Vancouver",
"lat": 49.261226,
"lng": -123.113927
},
"u": []
}
~~~

Usually the "u" parameter contains one or two Strings:

~~~
{
"id": "city-of-kingston/877",
"ty": "gtfsrealtime",
"t": "Kingston Transit Vehicle Positions",
"l": {
"id": 574,
"pid": 46,
"t": "Kingston, ON, Canada",
"n": "Kingston",
"lat": 44.231172,
"lng": -76.485954
},
"u": {
"i": "https://www.cityofkingston.ca/documents/10180/144997/GIS_OpenDataLicense.pdf/72f5a9ac-afbc-4fe3-959d-9111c9393bfa",
"d": "http://kingston.metrolinx.tmix.se/gtfs-realtime/vehicleupdates.pb"
}
},
~~~

I've pushed the full JSON response for setting up a unit test to the repo at https://raw.githubusercontent.com/CUTR-at-USF/transitfeeds-client-library/master/src/test/resources/get-feeds-realtime-url-array.json.

**Comment by barbeau** [comment]
Looks like configuring the `ObjectMapper` with:

`.configure(DeserializationFeature.ACCEPT_EMPTY_ARRAY_AS_NULL_OBJECT, true);`

...should solve this.
